### ISSUE TITLE
Requirements Gathering

### ISSUE THREAD

**Issue by MrME-CodeSmith** [COS301-MP-AboutTime/miniproject-2023#4]
Gather requirements for the project

- [x] Create Preliminary Functional Requirements - Thank you @LukeLawson-Tuks for completing this
- [x] Finalize Functional Requirements

**Comment by u19012366** [comment]
Thank you @LukeLawsonSoftware for the comprehensive Functional Requirements document based on the functionality discussed in the passed meetings.
