### ISSUE TITLE
Mock up and connect API functions (Profile)

### ISSUE THREAD

**Issue by LukeLawsonSoftware** [COS301-MP-AboutTime/miniproject-2023#66]

**Comment by Prometheus18082106** [comment]
Completed mock functions for Profile i.e commands and command handlers for the requests and responses

**Comment by Prometheus18082106** [comment]
Added the functions in other user.api.ts in the app/other-user/data-access folder to interact with the api.

**Comment by Prometheus18082106** [comment]
Added all the api mock implementations and interaction with other-user component for the updateRelation interaction

**Comment by Prometheus18082106** [comment]
All mock implementation and connection to API functions done
