### ISSUE TITLE
Implement Logic + Connect to state (Profile)

### ISSUE THREAD

**Issue by LukeLawsonSoftware** [COS301-MP-AboutTime/miniproject-2023#71]

**Comment by Prometheus18082106** [comment]
Profile api is now connected to the other-user state.

**Comment by Prometheus18082106** [comment]
Profile api connected to profile state.
Busy fixing issues with integration and bugs

**Comment by Prometheus18082106** [comment]
Profile and Other-user fully connected: state -> backend
